### ISSUE TITLE
Hot to run on iOS

### ISSUE THREAD

**Issue by dua8racer** [Rajatkalsotra/Face-Recognition-Flutter#10]
Before that I thank you for inspiring. I've run this application, for android version it works normally but for ios version it can't work.
I've changed the gpu delegate code 

```
final gpuDelegate = GpuDelegate(
      options: GpuDelegateOptions(true, TFLGpuDelegateWaitType.active),
    );
var interpreterOptions = InterpreterOptions()..addDelegate(gpuDelegate);
final interpreter = await Interpreter.fromAsset('your_model.tflite',
    options: interpreterOptions);
```

but still it doesn't work, is there a solution for working on ios
Thanks Before

**Comment by Rajatkalsotra** [comment]
@dua8racer Thanks for the big words . I've coded it for android only. 
Issue may be related to the output of camera format (android -> yuv and ios -> bgra) .Can you attach the error log?

**Comment by dua8racer** [comment]
Halo @Rajatkalsotra. error log :
`[lvl=3] +[FBMLx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.`
maybe this error on Firebase ML Kit, was because his face was not detected

**Comment by dua8racer** [comment]
Halo @Rajatkalsotra the error log is 
`An empty result was returned from GMVDetector in VisionFaceDetector.`

**Comment by dua8racer** [comment]
Halo @Rajatkalsotra, right what you say. Issue output camera format.
i found solution
```
imglib.Image _convertBGRA8888(CameraImage image, CameraLensDirection _dir) {
    
    imglib.Image img = imglib.Image.fromBytes(
      image.width,
      image.height,
      image.planes[0].bytes,
      format: imglib.Format.bgra,
    );
    var img1 = (_dir == CameraLensDirection.front)
        ? imglib.copyRotate(img, -90)
        : imglib.copyRotate(img, 90);
    return img1;

  }
```
