### ISSUE TITLE
ERROR: Unhandled Exception: Invalid arguments(s): Unable to create interpreter

### ISSUE THREAD

**Issue by adityariyadi** [Rajatkalsotra/Face-Recognition-Flutter#5]
Hi,

I download the code and build apk on Flutter Android Studio, but it fails on main.dart line 64. Unable to create interpreter. So I down load APK from this repo, but it won't install at all. I am using android version 5.0.

From the log I found that when Initialize TensorFlow lite runtime L2_NORMALIZATION: Operation is not supported, and 2 lines after that : OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found.

Could you help? Thank you.

Aditya

**Comment by adityariyadi** [comment]
I try with android version 6.0, now it works. The error disappear. But I couldn't get face. So FAB is in disable state, Could be a face detection problem?

**Comment by Rajatkalsotra** [comment]
The issue _"OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so"_ may be because of the addition of GPU delegate usage in code.You may try to remove delegate usage for android 5.0.
https://github.com/Rajatkalsotra/Face-Recognition-Flutter/blob/5ab50add873bb9ea20c031fe523ba81cee6a0725/lib/main.dart#L53-L65

**Comment by Rajatkalsotra** [comment]
@adityariyadi If face is not getting detected , then try other camera resolutions (here I've chosen low).

**Comment by adityariyadi** [comment]
@Rajatkalsotra Now it works on Android version 5, after removing delegate. I have to replace camera with image picker and modify some codes to make it working with image picker and able to get faces and also detects faces. It works very well. But my mobile phone is too slow to process stream of images using camera (old phones :=)). Will try again later with camera after trying to find cellphone with faster CPU/GPU. Thank you.

**Comment by adityariyadi** [comment]
Since it already working with older phone (Lollipop and Marshmallow), I think I close this issue.

**Comment by gilmarmontero** [comment]
Download the project and it works perfectly, but when I try to implement it as a module from another project it gives an error when calling the load model. Could you tell me what it can be?
