### ISSUE TITLE
error when calling load method.

### ISSUE THREAD

**Issue by gilmarmontero** [Rajatkalsotra/Face-Recognition-Flutter#6]
Download the project and it works perfectly, but when I try to implement it as a module from another project it gives an error when calling the load model. Could you tell me what it can be?

**Comment by tmtit** [comment]
Did you resolve it? Im facing the same error.
Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libtensorflowlite_c.so" not found)

**Comment by Rajatkalsotra** [comment]
@gilmarmontero @tmtit Well for **tflite_flutter** package to work you need to download few dynamic libraries.Please go through the below link.

<https://pub.dev/packages/tflite_flutter#important-initial-setup>

**Comment by tmtit** [comment]
@Rajatkalsotra Thank you very much

**Comment by gilmarmontero** [comment]
oops! It worked here. thank you

**Comment by deepsingh132** [comment]
@Rajatkalsotra Hey Great App ! But can you tell me why it lags a lot ? Idk if that's only happening to me or anyone else

**Comment by Rajatkalsotra** [comment]
@deepsingh132 It is supposed to be slow as most of the processes are being executed using CPU and GPU delegate is being used only when preprocessed image is passed to tensorflow model and it outputs the embeddings. Well still, performance can be improved  a lot and I'm looking towards it. Anyway thanks for using the app and liking it.

**Comment by rubana28** [comment]
> @gilmarmontero @tmtit Well for **tflite_flutter** package to work you need to download few dynamic libraries.Please go through the below link.
> 
> https://pub.dev/packages/tflite_flutter#important-initial-setup

Hey I am still confused about where I should place the install. sh file and from where I should execute it. Can you please help me with that information? @Rajatkalsotra

**Comment by tayabdev** [comment]
> > @gilmarmontero @tmtit Well for **tflite_flutter** package to work you need to download few dynamic libraries.Please go through the below link.
> > https://pub.dev/packages/tflite_flutter#important-initial-setup
> 
> Hey I am still confused about where I should place the install. sh file and from where I should execute it. Can you please help me with that information? @Rajatkalsotra

place install.bat file inside lib and run .\install.bat from your terminal in lib directory
